vich_uploader:
    db_driver: orm

    mappings:
        post_article_image:
            uri_prefix: /upload/images/post-articles
            upload_destination: '%kernel.project_dir%/public/upload/images/post-articles'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
